export const aura = {
  name: 'Aura',
  description: 'Deep slate with champagne gold and frosted glass',
  colors: {
    bg: '#0D1117',
    surface: '#161B22',
    surfaceAlt: 'rgba(255,255,255,0.04)',
    accent: '#C9A96E',
    accentSecondary: '#00FFCC',
    text: '#E6EDF3',
    textSecondary: '#8B949E',
    border: '#30363D',
    cardBg: 'rgba(255,255,255,0.04)',
    cardBorder: 'rgba(255,255,255,0.08)',
    sleep: '#8B5CF6',
    activity: '#00FFCC',
    readiness: '#C9A96E',
    strain: '#C9A96E',
  },
  fonts: {
    heading: "'SF Pro Display', -apple-system, sans-serif",
    body: "'SF Pro Text', -apple-system, sans-serif",
    mono: "'SF Mono', monospace",
  },
  style: {
    cardRadius: '16px',
    cardBorder: '1px solid rgba(255,255,255,0.08)',
    cardShadow: 'none',
    headingWeight: '500',
    numberFont: "'SF Pro Display', -apple-system, sans-serif",
    numberWeight: '600',
    isLight: false,
    frosted: true,
  },
};
