export const bevel = {
  name: 'Bevel Premium',
  description: 'Bold strain/recovery scoring with electric coral',
  colors: {
    bg: '#0F0F0F',
    surface: '#1A1A1A',
    surfaceAlt: '#222222',
    accent: '#FF6B35',
    accentSecondary: '#4ECDC4',
    text: '#FFFFFF',
    textSecondary: '#999999',
    border: '#333333',
    cardBg: '#1A1A1A',
    cardBorder: '#333333',
    sleep: '#9B59B6',
    activity: '#FF6B35',
    readiness: '#4ECDC4',
    strain: '#FF6B35',
  },
  fonts: {
    heading: "'SF Pro Display', -apple-system, sans-serif",
    body: "'SF Pro Text', -apple-system, sans-serif",
    mono: "'SF Mono', monospace",
  },
  style: {
    cardRadius: '16px',
    cardBorder: '1px solid #333333',
    cardShadow: 'none',
    headingWeight: '900',
    numberFont: "'SF Pro Display', -apple-system, sans-serif",
    numberWeight: '900',
    isLight: false,
    hasFAB: true,
    scoreSize: '72px',
  },
};
