export const hybrid = {
  name: 'Oura × Bevel',
  description: 'Circular rings in structured card grids — best of both',
  colors: {
    bg: '#0F1218',
    surface: '#181E28',
    surfaceAlt: '#1E2535',
    accent: '#E8A04B',
    accentSecondary: '#FF8C42',
    text: '#F0F4F8',
    textSecondary: '#8899AA',
    border: '#2A3545',
    cardBg: '#181E28',
    cardBorder: '#2A3545',
    sleep: '#4A90D9',
    activity: '#FF8C42',
    readiness: '#E8A04B',
    strain: '#FF8C42',
  },
  fonts: {
    heading: "'SF Pro Display', -apple-system, sans-serif",
    body: "'SF Pro Text', -apple-system, sans-serif",
    mono: "'SF Mono', monospace",
  },
  style: {
    cardRadius: '16px',
    cardBorder: '1px solid #2A3545',
    cardShadow: 'none',
    headingWeight: '700',
    numberFont: "'SF Pro Display', -apple-system, sans-serif",
    numberWeight: '700',
    isLight: false,
    hasFAB: true,
  },
};
