export const meridian = {
  name: 'Meridian',
  description: 'Clean iOS-native design with system blue',
  colors: {
    bg: '#F2F2F7',
    surface: '#FFFFFF',
    surfaceAlt: '#E5E5EA',
    accent: '#007AFF',
    accentSecondary: '#34C759',
    text: '#000000',
    textSecondary: '#6C6C70',
    border: '#D1D1D6',
    cardBg: '#FFFFFF',
    cardBorder: 'transparent',
    sleep: '#5856D6',
    activity: '#34C759',
    readiness: '#007AFF',
    strain: '#FF9500',
  },
  fonts: {
    heading: "-apple-system, 'SF Pro Display', sans-serif",
    body: "-apple-system, 'SF Pro Text', sans-serif",
    mono: "'SF Mono', monospace",
  },
  style: {
    cardRadius: '12px',
    cardBorder: 'none',
    cardShadow: '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)',
    headingWeight: '600',
    numberFont: "-apple-system, 'SF Pro Display', sans-serif",
    numberWeight: '700',
    isLight: true,
  },
};
