export const obsidian = {
  name: 'Obsidian',
  description: 'OLED black with electric indigo data displays',
  colors: {
    bg: '#000000',
    surface: '#0A0A0A',
    surfaceAlt: '#111111',
    accent: '#7C6EFA',
    accentSecondary: '#7C6EFA',
    text: '#FFFFFF',
    textSecondary: '#888899',
    border: '#1E1E2E',
    cardBg: 'transparent',
    cardBorder: '#1E1E2E',
    sleep: '#7C6EFA',
    activity: '#30D158',
    readiness: '#7C6EFA',
    strain: '#7C6EFA',
  },
  fonts: {
    heading: "'SF Pro Display', -apple-system, sans-serif",
    body: "'SF Pro Text', -apple-system, sans-serif",
    mono: "'SF Mono', monospace",
  },
  style: {
    cardRadius: '12px',
    cardBorder: '1px solid #1E1E2E',
    cardShadow: 'none',
    headingWeight: '700',
    numberFont: "'SF Mono', monospace",
    numberWeight: '700',
    isLight: false,
  },
};
