export const oura = {
  name: 'Oura Premium',
  description: 'Circular rings with warm amber and deep navy',
  colors: {
    bg: '#0B0E13',
    surface: '#131920',
    surfaceAlt: '#1E2530',
    accent: '#E8A04B',
    accentSecondary: '#4A90D9',
    text: '#EAEAEA',
    textSecondary: '#7A8899',
    border: '#2A3545',
    cardBg: '#131920',
    cardBorder: '#2A3545',
    sleep: '#4A90D9',
    activity: '#30D158',
    readiness: '#E8A04B',
    strain: '#E8A04B',
  },
  fonts: {
    heading: "'SF Pro Display', -apple-system, sans-serif",
    body: "'SF Pro Text', -apple-system, sans-serif",
    mono: "'SF Mono', monospace",
  },
  style: {
    cardRadius: '16px',
    cardBorder: '1px solid #2A3545',
    cardShadow: 'none',
    headingWeight: '600',
    numberFont: "'SF Pro Display', -apple-system, sans-serif",
    numberWeight: '600',
    isLight: false,
    tabs: ['Today', 'Vitals', 'My Health'],
    tabEmojis: ['🏠', '❤️', '👤'],
  },
};
