export const solstice = {
  name: 'Solstice',
  description: 'Warm parchment tones with editorial serif typography',
  colors: {
    bg: '#1A1410',
    surface: '#231C15',
    surfaceAlt: '#2D2318',
    accent: '#D4845A',
    accentSecondary: '#7A9B76',
    text: '#F5EDD8',
    textSecondary: '#B8A48A',
    border: '#3D3228',
    cardBg: '#2D2318',
    cardBorder: '#3D3228',
    sleep: '#7A9B76',
    activity: '#D4845A',
    readiness: '#D4845A',
    strain: '#D4845A',
  },
  fonts: {
    heading: "Georgia, 'New York', serif",
    body: "'SF Pro Text', -apple-system, sans-serif",
    mono: "'SF Mono', monospace",
  },
  style: {
    cardRadius: '12px',
    cardBorder: '1px solid #3D3228',
    cardShadow: 'none',
    headingWeight: '600',
    numberFont: "Georgia, 'New York', serif",
    numberWeight: '700',
    isLight: false,
  },
};
