export const voltage = {
  name: 'Voltage',
  description: 'Chartreuse neon with gym energy aesthetics',
  colors: {
    bg: '#0A0A00',
    surface: '#111100',
    surfaceAlt: '#1A1A00',
    accent: '#CCFF00',
    accentSecondary: '#CCFF00',
    text: '#FFFFFF',
    textSecondary: '#888877',
    border: '#2A2A00',
    cardBg: '#111100',
    cardBorder: '#2A2A00',
    sleep: '#CCFF00',
    activity: '#CCFF00',
    readiness: '#CCFF00',
    strain: '#CCFF00',
  },
  fonts: {
    heading: "'SF Pro Display', -apple-system, sans-serif",
    body: "'SF Pro Text', -apple-system, sans-serif",
    mono: "'SF Mono', monospace",
  },
  style: {
    cardRadius: '12px',
    cardBorder: '1px solid #2A2A00',
    cardShadow: 'none',
    headingWeight: '900',
    numberFont: "'SF Pro Display', -apple-system, sans-serif",
    numberWeight: '900',
    isLight: false,
  },
};
